version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: octobot_server_1
      APP_PORT: 5001

  server:
    image: ghcr.io/drakkarsoftware/octobot:stable
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/logs:/octobot/logs
      - ${APP_DATA_DIR}/backtesting:/octobot/backtesting
      - ${APP_DATA_DIR}/tentacles:/octobot/tentacles
      - ${APP_DATA_DIR}/user:/octobot/user
    ports:
      - "80:5001"

  watchtower:
    image: containrrr/watchtower
    restart: on-failure
    command: --cleanup --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock