version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: freqtrade_server_1
      APP_PORT: 8080
  server:
    image: ghcr.io/freqtrade/freqtrade:stable
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/freqtrade/user_data
    ports:
      - "8080:8080"
    command: trade --strategy SampleStrategy