version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: ducas-freqtrade_server_1
      APP_PORT: 8080

  server:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/user_data:/freqtrade/user_data
    expose:
      - 8080
    container_name: ducas-freqtrade_server_1
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy