version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: ducas-TradingView-Free-Webhook-Alerts_server_1
      APP_PORT: 12345
      PROXY_AUTH_ADD: 'true'
    container_name: ducas-TradingView-Free-Webhook-Alerts_app_proxy_1

  server:
    image: tradingview-free-webhook-alerts/freqtrade:stable
    restart: always
    volumes:
      - ${APP_DATA_DIR}/user_data:/freqtrade/user_data
    ports:
      - 8080
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy